"""Initial schema for Medical Records Service

Revision ID: 7eb086d8a208
Revises: 
Create Date: 2025-09-11 23:49:19.696519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7eb086d8a208'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medical_histories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('family_history', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('genetic_conditions', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('smoking_status', sa.String(length=50), nullable=True),
    sa.Column('alcohol_use', sa.String(length=50), nullable=True),
    sa.Column('drug_use', sa.String(length=50), nullable=True),
    sa.Column('occupation_history', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('travel_history', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('known_allergies', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('drug_allergies', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('environmental_allergies', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('food_allergies', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('chronic_conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('past_surgeries', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('past_hospitalizations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reproductive_history', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('pregnancy_history', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('vaccination_history', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('immunization_status', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('active_problems', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('resolved_problems', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('current_medications', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('medication_allergies', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('emergency_information', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('advance_directives', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_review_date', sa.Date(), nullable=True),
    sa.Column('last_reviewed_by', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medical_histories_patient_id'), 'medical_histories', ['patient_id'], unique=True)
    op.create_table('medical_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('record_number', sa.String(length=20), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('professional_id', sa.UUID(), nullable=False),
    sa.Column('appointment_id', sa.UUID(), nullable=True),
    sa.Column('record_type', sa.Enum('CONSULTATION', 'PROCEDURE', 'DIAGNOSIS', 'TREATMENT_PLAN', 'PRESCRIPTION', 'LAB_RESULT', 'IMAGING', 'VACCINATION', 'SURGERY', 'DISCHARGE_SUMMARY', 'EMERGENCY', 'FOLLOW_UP', name='recordtype'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'COMPLETED', 'ARCHIVED', 'DELETED', name='recordstatus'), nullable=False),
    sa.Column('record_date', sa.DateTime(), nullable=False),
    sa.Column('service_date', sa.Date(), nullable=True),
    sa.Column('chief_complaint', sa.Text(), nullable=True),
    sa.Column('history_present_illness', sa.Text(), nullable=True),
    sa.Column('review_of_systems', sa.Text(), nullable=True),
    sa.Column('physical_examination', sa.Text(), nullable=True),
    sa.Column('primary_diagnosis', sa.Text(), nullable=True),
    sa.Column('secondary_diagnoses', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('differential_diagnoses', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('icd_codes', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('treatment_plan', sa.Text(), nullable=True),
    sa.Column('medications_prescribed', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('procedures_performed', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('recommendations', sa.Text(), nullable=True),
    sa.Column('follow_up_instructions', sa.Text(), nullable=True),
    sa.Column('next_appointment_recommended', sa.Date(), nullable=True),
    sa.Column('vital_signs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('clinical_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_sensitive', sa.Boolean(), nullable=False),
    sa.Column('access_level', sa.String(length=20), nullable=False),
    sa.Column('encryption_key_id', sa.String(length=100), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('verified_by', sa.UUID(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medical_records_appointment_id'), 'medical_records', ['appointment_id'], unique=False)
    op.create_index(op.f('ix_medical_records_patient_id'), 'medical_records', ['patient_id'], unique=False)
    op.create_index(op.f('ix_medical_records_professional_id'), 'medical_records', ['professional_id'], unique=False)
    op.create_index(op.f('ix_medical_records_record_date'), 'medical_records', ['record_date'], unique=False)
    op.create_index(op.f('ix_medical_records_record_number'), 'medical_records', ['record_number'], unique=True)
    op.create_index(op.f('ix_medical_records_record_type'), 'medical_records', ['record_type'], unique=False)
    op.create_table('medical_records_audit',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('user_role', sa.String(length=50), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('action_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medical_records_audit_action'), 'medical_records_audit', ['action'], unique=False)
    op.create_index(op.f('ix_medical_records_audit_created_at'), 'medical_records_audit', ['created_at'], unique=False)
    op.create_index(op.f('ix_medical_records_audit_patient_id'), 'medical_records_audit', ['patient_id'], unique=False)
    op.create_index(op.f('ix_medical_records_audit_resource_id'), 'medical_records_audit', ['resource_id'], unique=False)
    op.create_index(op.f('ix_medical_records_audit_resource_type'), 'medical_records_audit', ['resource_type'], unique=False)
    op.create_index(op.f('ix_medical_records_audit_user_id'), 'medical_records_audit', ['user_id'], unique=False)
    op.create_table('lab_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('medical_record_id', sa.UUID(), nullable=True),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('lab_order_number', sa.String(length=50), nullable=True),
    sa.Column('external_lab_id', sa.String(length=100), nullable=True),
    sa.Column('lab_name', sa.String(length=255), nullable=False),
    sa.Column('test_name', sa.String(length=255), nullable=False),
    sa.Column('test_code', sa.String(length=50), nullable=True),
    sa.Column('test_category', sa.String(length=100), nullable=False),
    sa.Column('specimen_type', sa.String(length=100), nullable=True),
    sa.Column('ordered_date', sa.DateTime(), nullable=False),
    sa.Column('collected_date', sa.DateTime(), nullable=True),
    sa.Column('reported_date', sa.DateTime(), nullable=False),
    sa.Column('verified_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('ORDERED', 'COLLECTED', 'PROCESSING', 'COMPLETED', 'CANCELLED', 'ABNORMAL', name='labteststatus'), nullable=False),
    sa.Column('result_value', sa.String(length=100), nullable=True),
    sa.Column('result_unit', sa.String(length=50), nullable=True),
    sa.Column('reference_range', sa.String(length=100), nullable=True),
    sa.Column('is_abnormal', sa.Boolean(), nullable=True),
    sa.Column('abnormal_flag', sa.String(length=10), nullable=True),
    sa.Column('interpretation', sa.Text(), nullable=True),
    sa.Column('clinical_significance', sa.Text(), nullable=True),
    sa.Column('recommendations', sa.Text(), nullable=True),
    sa.Column('ordering_professional', sa.UUID(), nullable=False),
    sa.Column('reviewing_professional', sa.UUID(), nullable=True),
    sa.Column('result_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('quality_control', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('technical_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['medical_record_id'], ['medical_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lab_results_lab_order_number'), 'lab_results', ['lab_order_number'], unique=False)
    op.create_index(op.f('ix_lab_results_medical_record_id'), 'lab_results', ['medical_record_id'], unique=False)
    op.create_index(op.f('ix_lab_results_patient_id'), 'lab_results', ['patient_id'], unique=False)
    op.create_index(op.f('ix_lab_results_status'), 'lab_results', ['status'], unique=False)
    op.create_index(op.f('ix_lab_results_test_category'), 'lab_results', ['test_category'], unique=False)
    op.create_index(op.f('ix_lab_results_test_code'), 'lab_results', ['test_code'], unique=False)
    op.create_table('medical_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('medical_record_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.Enum('LAB_REPORT', 'IMAGING_SCAN', 'PRESCRIPTION', 'REFERRAL', 'MEDICAL_CERTIFICATE', 'VACCINATION_CARD', 'SURGERY_REPORT', 'PATHOLOGY_REPORT', 'CONSENT_FORM', 'INSURANCE_FORM', 'OTHER', name='documenttype'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('UPLOADED', 'PROCESSING', 'VERIFIED', 'REJECTED', 'ARCHIVED', name='documentstatus'), nullable=False),
    sa.Column('processing_status', sa.String(length=50), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('ocr_confidence', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('is_encrypted', sa.Boolean(), nullable=False),
    sa.Column('encryption_key_id', sa.String(length=100), nullable=True),
    sa.Column('is_phi', sa.Boolean(), nullable=False),
    sa.Column('document_date', sa.Date(), nullable=True),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('institution', sa.String(length=255), nullable=True),
    sa.Column('external_id', sa.String(length=100), nullable=True),
    sa.Column('access_level', sa.String(length=20), nullable=False),
    sa.Column('viewable_by_patient', sa.Boolean(), nullable=False),
    sa.Column('sharing_permissions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('keywords', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('clinical_categories', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('last_accessed', sa.DateTime(), nullable=True),
    sa.Column('access_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['medical_record_id'], ['medical_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medical_documents_document_type'), 'medical_documents', ['document_type'], unique=False)
    op.create_index(op.f('ix_medical_documents_medical_record_id'), 'medical_documents', ['medical_record_id'], unique=False)
    op.create_table('prescriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('medical_record_id', sa.UUID(), nullable=True),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('prescription_number', sa.String(length=20), nullable=False),
    sa.Column('medication_name', sa.String(length=255), nullable=False),
    sa.Column('generic_name', sa.String(length=255), nullable=True),
    sa.Column('medication_code', sa.String(length=50), nullable=True),
    sa.Column('strength', sa.String(length=50), nullable=True),
    sa.Column('dosage_form', sa.String(length=50), nullable=True),
    sa.Column('dosage', sa.String(length=255), nullable=False),
    sa.Column('frequency', sa.String(length=100), nullable=False),
    sa.Column('duration', sa.String(length=100), nullable=True),
    sa.Column('quantity', sa.String(length=50), nullable=True),
    sa.Column('refills', sa.Integer(), nullable=False),
    sa.Column('administration_route', sa.String(length=50), nullable=True),
    sa.Column('special_instructions', sa.Text(), nullable=True),
    sa.Column('food_instructions', sa.String(length=255), nullable=True),
    sa.Column('warnings', sa.Text(), nullable=True),
    sa.Column('prescribed_date', sa.DateTime(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_controlled_substance', sa.Boolean(), nullable=False),
    sa.Column('requires_monitoring', sa.Boolean(), nullable=False),
    sa.Column('prescribing_professional', sa.UUID(), nullable=False),
    sa.Column('professional_license', sa.String(length=50), nullable=True),
    sa.Column('pharmacy_instructions', sa.Text(), nullable=True),
    sa.Column('substitution_allowed', sa.Boolean(), nullable=False),
    sa.Column('adherence_notes', sa.Text(), nullable=True),
    sa.Column('side_effects', sa.Text(), nullable=True),
    sa.Column('effectiveness_notes', sa.Text(), nullable=True),
    sa.Column('indication', sa.String(length=255), nullable=True),
    sa.Column('contraindications', sa.Text(), nullable=True),
    sa.Column('drug_interactions', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['medical_record_id'], ['medical_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prescriptions_medical_record_id'), 'prescriptions', ['medical_record_id'], unique=False)
    op.create_index(op.f('ix_prescriptions_patient_id'), 'prescriptions', ['patient_id'], unique=False)
    op.create_index(op.f('ix_prescriptions_prescription_number'), 'prescriptions', ['prescription_number'], unique=True)
    op.create_table('vital_signs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('medical_record_id', sa.UUID(), nullable=True),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('measured_at', sa.DateTime(), nullable=False),
    sa.Column('systolic_bp', sa.Integer(), nullable=True),
    sa.Column('diastolic_bp', sa.Integer(), nullable=True),
    sa.Column('heart_rate', sa.Integer(), nullable=True),
    sa.Column('respiratory_rate', sa.Integer(), nullable=True),
    sa.Column('temperature_celsius', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('oxygen_saturation', sa.Integer(), nullable=True),
    sa.Column('height_cm', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('weight_kg', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('bmi', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('glucose_level', sa.Integer(), nullable=True),
    sa.Column('pain_scale', sa.Integer(), nullable=True),
    sa.Column('position', sa.String(length=50), nullable=True),
    sa.Column('activity_level', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('measurement_method', sa.String(length=100), nullable=True),
    sa.Column('device_used', sa.String(length=255), nullable=True),
    sa.Column('device_calibration_date', sa.Date(), nullable=True),
    sa.Column('is_critical', sa.Boolean(), nullable=False),
    sa.Column('critical_values', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('alerts_triggered', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('measured_by', sa.UUID(), nullable=False),
    sa.Column('verified_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['medical_record_id'], ['medical_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vital_signs_measured_at'), 'vital_signs', ['measured_at'], unique=False)
    op.create_index(op.f('ix_vital_signs_medical_record_id'), 'vital_signs', ['medical_record_id'], unique=False)
    op.create_index(op.f('ix_vital_signs_patient_id'), 'vital_signs', ['patient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vital_signs_patient_id'), table_name='vital_signs')
    op.drop_index(op.f('ix_vital_signs_medical_record_id'), table_name='vital_signs')
    op.drop_index(op.f('ix_vital_signs_measured_at'), table_name='vital_signs')
    op.drop_table('vital_signs')
    op.drop_index(op.f('ix_prescriptions_prescription_number'), table_name='prescriptions')
    op.drop_index(op.f('ix_prescriptions_patient_id'), table_name='prescriptions')
    op.drop_index(op.f('ix_prescriptions_medical_record_id'), table_name='prescriptions')
    op.drop_table('prescriptions')
    op.drop_index(op.f('ix_medical_documents_medical_record_id'), table_name='medical_documents')
    op.drop_index(op.f('ix_medical_documents_document_type'), table_name='medical_documents')
    op.drop_table('medical_documents')
    op.drop_index(op.f('ix_lab_results_test_code'), table_name='lab_results')
    op.drop_index(op.f('ix_lab_results_test_category'), table_name='lab_results')
    op.drop_index(op.f('ix_lab_results_status'), table_name='lab_results')
    op.drop_index(op.f('ix_lab_results_patient_id'), table_name='lab_results')
    op.drop_index(op.f('ix_lab_results_medical_record_id'), table_name='lab_results')
    op.drop_index(op.f('ix_lab_results_lab_order_number'), table_name='lab_results')
    op.drop_table('lab_results')
    op.drop_index(op.f('ix_medical_records_audit_user_id'), table_name='medical_records_audit')
    op.drop_index(op.f('ix_medical_records_audit_resource_type'), table_name='medical_records_audit')
    op.drop_index(op.f('ix_medical_records_audit_resource_id'), table_name='medical_records_audit')
    op.drop_index(op.f('ix_medical_records_audit_patient_id'), table_name='medical_records_audit')
    op.drop_index(op.f('ix_medical_records_audit_created_at'), table_name='medical_records_audit')
    op.drop_index(op.f('ix_medical_records_audit_action'), table_name='medical_records_audit')
    op.drop_table('medical_records_audit')
    op.drop_index(op.f('ix_medical_records_record_type'), table_name='medical_records')
    op.drop_index(op.f('ix_medical_records_record_number'), table_name='medical_records')
    op.drop_index(op.f('ix_medical_records_record_date'), table_name='medical_records')
    op.drop_index(op.f('ix_medical_records_professional_id'), table_name='medical_records')
    op.drop_index(op.f('ix_medical_records_patient_id'), table_name='medical_records')
    op.drop_index(op.f('ix_medical_records_appointment_id'), table_name='medical_records')
    op.drop_table('medical_records')
    op.drop_index(op.f('ix_medical_histories_patient_id'), table_name='medical_histories')
    op.drop_table('medical_histories')
    # ### end Alembic commands ###
