"""Initial schema for Notification Service

Revision ID: 6e7a0fdc03f1
Revises: 
Create Date: 2025-09-11 23:49:35.763481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6e7a0fdc03f1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_preferences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('notification_type', sa.Enum('APPOINTMENT_REMINDER', 'APPOINTMENT_CONFIRMATION', 'APPOINTMENT_CANCELLATION', 'APPOINTMENT_RESCHEDULED', 'PAYMENT_CONFIRMATION', 'PAYMENT_FAILED', 'INVOICE_CREATED', 'INVOICE_OVERDUE', 'LAB_RESULTS_READY', 'PRESCRIPTION_READY', 'WELCOME', 'PASSWORD_RESET', 'ACCOUNT_VERIFICATION', 'SECURITY_ALERT', 'SYSTEM_MAINTENANCE', 'PROMOTIONAL', 'CUSTOM', name='notificationtype'), nullable=False),
    sa.Column('email_enabled', sa.Boolean(), nullable=False),
    sa.Column('sms_enabled', sa.Boolean(), nullable=False),
    sa.Column('whatsapp_enabled', sa.Boolean(), nullable=False),
    sa.Column('push_enabled', sa.Boolean(), nullable=False),
    sa.Column('in_app_enabled', sa.Boolean(), nullable=False),
    sa.Column('quiet_hours_start', sa.String(length=5), nullable=True),
    sa.Column('quiet_hours_end', sa.String(length=5), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('frequency', sa.String(length=20), nullable=False),
    sa.Column('max_per_day', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('priority_threshold', sa.Enum('LOW', 'NORMAL', 'HIGH', 'URGENT', 'CRITICAL', name='priority'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_preferences_notification_type'), 'notification_preferences', ['notification_type'], unique=False)
    op.create_index(op.f('ix_notification_preferences_user_id'), 'notification_preferences', ['user_id'], unique=False)
    op.create_table('notification_statistics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('email_sent', sa.Integer(), nullable=False),
    sa.Column('email_delivered', sa.Integer(), nullable=False),
    sa.Column('email_opened', sa.Integer(), nullable=False),
    sa.Column('email_clicked', sa.Integer(), nullable=False),
    sa.Column('email_failed', sa.Integer(), nullable=False),
    sa.Column('sms_sent', sa.Integer(), nullable=False),
    sa.Column('sms_delivered', sa.Integer(), nullable=False),
    sa.Column('sms_failed', sa.Integer(), nullable=False),
    sa.Column('whatsapp_sent', sa.Integer(), nullable=False),
    sa.Column('whatsapp_delivered', sa.Integer(), nullable=False),
    sa.Column('whatsapp_read', sa.Integer(), nullable=False),
    sa.Column('whatsapp_failed', sa.Integer(), nullable=False),
    sa.Column('push_sent', sa.Integer(), nullable=False),
    sa.Column('push_delivered', sa.Integer(), nullable=False),
    sa.Column('push_opened', sa.Integer(), nullable=False),
    sa.Column('push_failed', sa.Integer(), nullable=False),
    sa.Column('total_sent', sa.Integer(), nullable=False),
    sa.Column('total_delivered', sa.Integer(), nullable=False),
    sa.Column('total_failed', sa.Integer(), nullable=False),
    sa.Column('delivery_rate', sa.String(length=10), nullable=True),
    sa.Column('open_rate', sa.String(length=10), nullable=True),
    sa.Column('click_rate', sa.String(length=10), nullable=True),
    sa.Column('channel', sa.Enum('EMAIL', 'SMS', 'WHATSAPP', 'PUSH', 'IN_APP', 'WEBHOOK', name='notificationchannel'), nullable=True),
    sa.Column('notification_type', sa.Enum('APPOINTMENT_REMINDER', 'APPOINTMENT_CONFIRMATION', 'APPOINTMENT_CANCELLATION', 'APPOINTMENT_RESCHEDULED', 'PAYMENT_CONFIRMATION', 'PAYMENT_FAILED', 'INVOICE_CREATED', 'INVOICE_OVERDUE', 'LAB_RESULTS_READY', 'PRESCRIPTION_READY', 'WELCOME', 'PASSWORD_RESET', 'ACCOUNT_VERIFICATION', 'SECURITY_ALERT', 'SYSTEM_MAINTENANCE', 'PROMOTIONAL', 'CUSTOM', name='notificationtype'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_statistics_channel'), 'notification_statistics', ['channel'], unique=False)
    op.create_index(op.f('ix_notification_statistics_date'), 'notification_statistics', ['date'], unique=False)
    op.create_index(op.f('ix_notification_statistics_notification_type'), 'notification_statistics', ['notification_type'], unique=False)
    op.create_table('notification_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('channel', sa.Enum('EMAIL', 'SMS', 'WHATSAPP', 'PUSH', 'IN_APP', 'WEBHOOK', name='notificationchannel'), nullable=False),
    sa.Column('notification_type', sa.Enum('APPOINTMENT_REMINDER', 'APPOINTMENT_CONFIRMATION', 'APPOINTMENT_CANCELLATION', 'APPOINTMENT_RESCHEDULED', 'PAYMENT_CONFIRMATION', 'PAYMENT_FAILED', 'INVOICE_CREATED', 'INVOICE_OVERDUE', 'LAB_RESULTS_READY', 'PRESCRIPTION_READY', 'WELCOME', 'PASSWORD_RESET', 'ACCOUNT_VERIFICATION', 'SECURITY_ALERT', 'SYSTEM_MAINTENANCE', 'PROMOTIONAL', 'CUSTOM', name='notificationtype'), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('subject_template', sa.String(length=500), nullable=True),
    sa.Column('content_template', sa.Text(), nullable=False),
    sa.Column('html_template', sa.Text(), nullable=True),
    sa.Column('variables', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sample_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'DEPRECATED', 'ARCHIVED', name='templatestatus'), nullable=False),
    sa.Column('is_system_template', sa.Boolean(), nullable=False),
    sa.Column('version', sa.String(length=10), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('usage_notes', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('default_priority', sa.Enum('LOW', 'NORMAL', 'HIGH', 'URGENT', 'CRITICAL', name='priority'), nullable=False),
    sa.Column('track_opens', sa.Boolean(), nullable=False),
    sa.Column('track_clicks', sa.Boolean(), nullable=False),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_templates_category'), 'notification_templates', ['category'], unique=False)
    op.create_index(op.f('ix_notification_templates_channel'), 'notification_templates', ['channel'], unique=False)
    op.create_index(op.f('ix_notification_templates_code'), 'notification_templates', ['code'], unique=True)
    op.create_index(op.f('ix_notification_templates_name'), 'notification_templates', ['name'], unique=False)
    op.create_index(op.f('ix_notification_templates_notification_type'), 'notification_templates', ['notification_type'], unique=False)
    op.create_table('webhook_endpoints',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('events', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('secret_key', sa.String(length=255), nullable=True),
    sa.Column('headers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('total_calls', sa.Integer(), nullable=False),
    sa.Column('successful_calls', sa.Integer(), nullable=False),
    sa.Column('failed_calls', sa.Integer(), nullable=False),
    sa.Column('last_called', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notification_campaigns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('campaign_id', sa.String(length=100), nullable=False),
    sa.Column('channel', sa.Enum('EMAIL', 'SMS', 'WHATSAPP', 'PUSH', 'IN_APP', 'WEBHOOK', name='notificationchannel'), nullable=False),
    sa.Column('notification_type', sa.Enum('APPOINTMENT_REMINDER', 'APPOINTMENT_CONFIRMATION', 'APPOINTMENT_CANCELLATION', 'APPOINTMENT_RESCHEDULED', 'PAYMENT_CONFIRMATION', 'PAYMENT_FAILED', 'INVOICE_CREATED', 'INVOICE_OVERDUE', 'LAB_RESULTS_READY', 'PRESCRIPTION_READY', 'WELCOME', 'PASSWORD_RESET', 'ACCOUNT_VERIFICATION', 'SECURITY_ALERT', 'SYSTEM_MAINTENANCE', 'PROMOTIONAL', 'CUSTOM', name='notificationtype'), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=True),
    sa.Column('target_audience', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('recipient_count', sa.Integer(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('sent_count', sa.Integer(), nullable=False),
    sa.Column('delivered_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('open_count', sa.Integer(), nullable=False),
    sa.Column('click_count', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['notification_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_campaigns_campaign_id'), 'notification_campaigns', ['campaign_id'], unique=True)
    op.create_index(op.f('ix_notification_campaigns_status'), 'notification_campaigns', ['status'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('notification_id', sa.String(length=50), nullable=False),
    sa.Column('recipient_id', sa.UUID(), nullable=False),
    sa.Column('recipient_email', sa.String(length=255), nullable=True),
    sa.Column('recipient_phone', sa.String(length=20), nullable=True),
    sa.Column('recipient_device_token', sa.String(length=500), nullable=True),
    sa.Column('sender_id', sa.UUID(), nullable=True),
    sa.Column('sender_name', sa.String(length=255), nullable=True),
    sa.Column('sender_email', sa.String(length=255), nullable=True),
    sa.Column('channel', sa.Enum('EMAIL', 'SMS', 'WHATSAPP', 'PUSH', 'IN_APP', 'WEBHOOK', name='notificationchannel'), nullable=False),
    sa.Column('notification_type', sa.Enum('APPOINTMENT_REMINDER', 'APPOINTMENT_CONFIRMATION', 'APPOINTMENT_CANCELLATION', 'APPOINTMENT_RESCHEDULED', 'PAYMENT_CONFIRMATION', 'PAYMENT_FAILED', 'INVOICE_CREATED', 'INVOICE_OVERDUE', 'LAB_RESULTS_READY', 'PRESCRIPTION_READY', 'WELCOME', 'PASSWORD_RESET', 'ACCOUNT_VERIFICATION', 'SECURITY_ALERT', 'SYSTEM_MAINTENANCE', 'PROMOTIONAL', 'CUSTOM', name='notificationtype'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'NORMAL', 'HIGH', 'URGENT', 'CRITICAL', name='priority'), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('html_content', sa.Text(), nullable=True),
    sa.Column('template_id', sa.UUID(), nullable=True),
    sa.Column('template_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'QUEUED', 'SENDING', 'SENT', 'DELIVERED', 'READ', 'FAILED', 'CANCELLED', 'SCHEDULED', name='notificationstatus'), nullable=False),
    sa.Column('delivery_status', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('send_after', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('queued_at', sa.DateTime(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('failed_at', sa.DateTime(), nullable=True),
    sa.Column('external_id', sa.String(length=100), nullable=True),
    sa.Column('external_status', sa.String(length=50), nullable=True),
    sa.Column('external_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('campaign_id', sa.String(length=100), nullable=True),
    sa.Column('is_bulk', sa.Boolean(), nullable=False),
    sa.Column('track_opens', sa.Boolean(), nullable=False),
    sa.Column('track_clicks', sa.Boolean(), nullable=False),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('device_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['notification_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_campaign_id'), 'notifications', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_notifications_channel'), 'notifications', ['channel'], unique=False)
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_external_id'), 'notifications', ['external_id'], unique=False)
    op.create_index(op.f('ix_notifications_notification_id'), 'notifications', ['notification_id'], unique=True)
    op.create_index(op.f('ix_notifications_notification_type'), 'notifications', ['notification_type'], unique=False)
    op.create_index(op.f('ix_notifications_recipient_id'), 'notifications', ['recipient_id'], unique=False)
    op.create_index(op.f('ix_notifications_scheduled_at'), 'notifications', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_notifications_sender_id'), 'notifications', ['sender_id'], unique=False)
    op.create_index(op.f('ix_notifications_status'), 'notifications', ['status'], unique=False)
    op.create_index(op.f('ix_notifications_template_id'), 'notifications', ['template_id'], unique=False)
    op.create_table('notification_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('notification_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('event_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('device_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('location_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('external_event_id', sa.String(length=100), nullable=True),
    sa.Column('provider_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('event_timestamp', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['notification_id'], ['notifications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_events_event_timestamp'), 'notification_events', ['event_timestamp'], unique=False)
    op.create_index(op.f('ix_notification_events_event_type'), 'notification_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_notification_events_notification_id'), 'notification_events', ['notification_id'], unique=False)
    op.create_table('notification_queue',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('notification_id', sa.UUID(), nullable=False),
    sa.Column('queue_name', sa.String(length=50), nullable=False),
    sa.Column('priority_score', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('worker_id', sa.String(length=100), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['notification_id'], ['notifications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_queue_notification_id'), 'notification_queue', ['notification_id'], unique=False)
    op.create_index(op.f('ix_notification_queue_priority_score'), 'notification_queue', ['priority_score'], unique=False)
    op.create_index(op.f('ix_notification_queue_queue_name'), 'notification_queue', ['queue_name'], unique=False)
    op.create_index(op.f('ix_notification_queue_scheduled_for'), 'notification_queue', ['scheduled_for'], unique=False)
    op.create_index(op.f('ix_notification_queue_status'), 'notification_queue', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notification_queue_status'), table_name='notification_queue')
    op.drop_index(op.f('ix_notification_queue_scheduled_for'), table_name='notification_queue')
    op.drop_index(op.f('ix_notification_queue_queue_name'), table_name='notification_queue')
    op.drop_index(op.f('ix_notification_queue_priority_score'), table_name='notification_queue')
    op.drop_index(op.f('ix_notification_queue_notification_id'), table_name='notification_queue')
    op.drop_table('notification_queue')
    op.drop_index(op.f('ix_notification_events_notification_id'), table_name='notification_events')
    op.drop_index(op.f('ix_notification_events_event_type'), table_name='notification_events')
    op.drop_index(op.f('ix_notification_events_event_timestamp'), table_name='notification_events')
    op.drop_table('notification_events')
    op.drop_index(op.f('ix_notifications_template_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_status'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_sender_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_scheduled_at'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_recipient_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_notification_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_notification_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_external_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_channel'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_campaign_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_notification_campaigns_status'), table_name='notification_campaigns')
    op.drop_index(op.f('ix_notification_campaigns_campaign_id'), table_name='notification_campaigns')
    op.drop_table('notification_campaigns')
    op.drop_table('webhook_endpoints')
    op.drop_index(op.f('ix_notification_templates_notification_type'), table_name='notification_templates')
    op.drop_index(op.f('ix_notification_templates_name'), table_name='notification_templates')
    op.drop_index(op.f('ix_notification_templates_code'), table_name='notification_templates')
    op.drop_index(op.f('ix_notification_templates_channel'), table_name='notification_templates')
    op.drop_index(op.f('ix_notification_templates_category'), table_name='notification_templates')
    op.drop_table('notification_templates')
    op.drop_index(op.f('ix_notification_statistics_notification_type'), table_name='notification_statistics')
    op.drop_index(op.f('ix_notification_statistics_date'), table_name='notification_statistics')
    op.drop_index(op.f('ix_notification_statistics_channel'), table_name='notification_statistics')
    op.drop_table('notification_statistics')
    op.drop_index(op.f('ix_notification_preferences_user_id'), table_name='notification_preferences')
    op.drop_index(op.f('ix_notification_preferences_notification_type'), table_name='notification_preferences')
    op.drop_table('notification_preferences')
    # ### end Alembic commands ###
