"""Initial schema for Appointment Service

Revision ID: ceaa5a577438
Revises: 
Create Date: 2025-09-11 23:49:10.051149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ceaa5a577438'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointment_locations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state_province', sa.String(length=100), nullable=False),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=11, scale=8), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('has_parking', sa.Boolean(), nullable=False),
    sa.Column('is_accessible', sa.Boolean(), nullable=False),
    sa.Column('available_services', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('equipment_available', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('operating_hours', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('holiday_schedule', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('special_instructions', sa.Text(), nullable=True),
    sa.Column('parking_instructions', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointment_locations_code'), 'appointment_locations', ['code'], unique=True)
    op.create_table('medical_services',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('specialty', sa.String(length=100), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('default_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('preparation_time_minutes', sa.Integer(), nullable=False),
    sa.Column('cleanup_time_minutes', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('requires_referral', sa.Boolean(), nullable=False),
    sa.Column('is_emergency_service', sa.Boolean(), nullable=False),
    sa.Column('telemedicine_available', sa.Boolean(), nullable=False),
    sa.Column('base_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('insurance_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('emergency_surcharge', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('age_restrictions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('gender_restrictions', sa.String(length=20), nullable=True),
    sa.Column('special_requirements', sa.Text(), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('contraindications', sa.Text(), nullable=True),
    sa.Column('equipment_needed', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medical_services_category'), 'medical_services', ['category'], unique=False)
    op.create_index(op.f('ix_medical_services_code'), 'medical_services', ['code'], unique=True)
    op.create_index(op.f('ix_medical_services_specialty'), 'medical_services', ['specialty'], unique=False)
    op.create_table('appointment_statistics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('total_appointments', sa.Integer(), nullable=False),
    sa.Column('completed_appointments', sa.Integer(), nullable=False),
    sa.Column('cancelled_appointments', sa.Integer(), nullable=False),
    sa.Column('no_show_appointments', sa.Integer(), nullable=False),
    sa.Column('rescheduled_appointments', sa.Integer(), nullable=False),
    sa.Column('emergency_appointments', sa.Integer(), nullable=False),
    sa.Column('telemedicine_appointments', sa.Integer(), nullable=False),
    sa.Column('walk_in_appointments', sa.Integer(), nullable=False),
    sa.Column('average_wait_time_minutes', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('average_duration_minutes', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('utilization_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('location_id', sa.UUID(), nullable=True),
    sa.Column('professional_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['appointment_locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointment_statistics_date'), 'appointment_statistics', ['date'], unique=False)
    op.create_table('appointments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('appointment_number', sa.String(length=20), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('professional_id', sa.UUID(), nullable=True),
    sa.Column('assigned_by', sa.UUID(), nullable=True),
    sa.Column('medical_service_id', sa.UUID(), nullable=False),
    sa.Column('appointment_type', sa.Enum('CONSULTATION', 'FOLLOW_UP', 'EMERGENCY', 'PROCEDURE', 'PREVENTIVE', 'SPECIALIST', 'TELEMEDICINE', name='appointmenttype'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'NORMAL', 'HIGH', 'URGENT', 'EMERGENCY', name='priority'), nullable=False),
    sa.Column('scheduled_date', sa.DateTime(), nullable=False),
    sa.Column('estimated_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('actual_start_time', sa.DateTime(), nullable=True),
    sa.Column('actual_end_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'NO_SHOW', 'RESCHEDULED', name='appointmentstatus'), nullable=False),
    sa.Column('previous_status', sa.Enum('PENDING', 'CONFIRMED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'NO_SHOW', 'RESCHEDULED', name='appointmentstatus'), nullable=True),
    sa.Column('status_changed_at', sa.DateTime(), nullable=True),
    sa.Column('status_changed_by', sa.UUID(), nullable=True),
    sa.Column('status_change_reason', sa.String(length=255), nullable=True),
    sa.Column('chief_complaint', sa.Text(), nullable=True),
    sa.Column('symptoms', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('special_instructions', sa.Text(), nullable=True),
    sa.Column('location_id', sa.UUID(), nullable=True),
    sa.Column('room_number', sa.String(length=20), nullable=True),
    sa.Column('is_telemedicine', sa.Boolean(), nullable=False),
    sa.Column('telemedicine_link', sa.String(length=500), nullable=True),
    sa.Column('payment_status', sa.Enum('PENDING', 'PAID', 'PARTIAL', 'REFUNDED', 'CANCELLED', name='paymentstatus'), nullable=False),
    sa.Column('estimated_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('final_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('insurance_covered', sa.Boolean(), nullable=False),
    sa.Column('reminder_sent', sa.Boolean(), nullable=False),
    sa.Column('confirmation_sent', sa.Boolean(), nullable=False),
    sa.Column('follow_up_required', sa.Boolean(), nullable=False),
    sa.Column('follow_up_date', sa.Date(), nullable=True),
    sa.Column('cancellation_reason', sa.String(length=255), nullable=True),
    sa.Column('cancelled_by', sa.UUID(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('reschedule_count', sa.Integer(), nullable=False),
    sa.Column('original_appointment_id', sa.UUID(), nullable=True),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('external_references', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['appointment_locations.id'], ),
    sa.ForeignKeyConstraint(['medical_service_id'], ['medical_services.id'], ),
    sa.ForeignKeyConstraint(['original_appointment_id'], ['appointments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointments_appointment_number'), 'appointments', ['appointment_number'], unique=True)
    op.create_index(op.f('ix_appointments_patient_id'), 'appointments', ['patient_id'], unique=False)
    op.create_index(op.f('ix_appointments_professional_id'), 'appointments', ['professional_id'], unique=False)
    op.create_index(op.f('ix_appointments_scheduled_date'), 'appointments', ['scheduled_date'], unique=False)
    op.create_index(op.f('ix_appointments_status'), 'appointments', ['status'], unique=False)
    op.create_table('professional_availability',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('professional_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'BUSY', 'BLOCKED', 'HOLIDAY', 'SICK_LEAVE', name='availabilitystatus'), nullable=False),
    sa.Column('is_recurring', sa.Boolean(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['appointment_locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_professional_availability_date'), 'professional_availability', ['date'], unique=False)
    op.create_index(op.f('ix_professional_availability_professional_id'), 'professional_availability', ['professional_id'], unique=False)
    op.create_table('professional_services',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('professional_id', sa.UUID(), nullable=False),
    sa.Column('medical_service_id', sa.UUID(), nullable=False),
    sa.Column('custom_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('custom_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('proficiency_level', sa.Integer(), nullable=False),
    sa.Column('certification_required', sa.Boolean(), nullable=False),
    sa.Column('certification_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('can_handle_emergency', sa.Boolean(), nullable=False),
    sa.Column('max_daily_appointments', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['medical_service_id'], ['medical_services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_professional_services_professional_id'), 'professional_services', ['professional_id'], unique=False)
    op.create_table('appointment_attachments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('appointment_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('attachment_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_encrypted', sa.Boolean(), nullable=False),
    sa.Column('access_level', sa.String(length=20), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointment_attachments_appointment_id'), 'appointment_attachments', ['appointment_id'], unique=False)
    op.create_table('appointment_reschedules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('appointment_id', sa.UUID(), nullable=False),
    sa.Column('original_date', sa.DateTime(), nullable=False),
    sa.Column('new_date', sa.DateTime(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('rescheduled_by', sa.UUID(), nullable=False),
    sa.Column('reschedule_type', sa.String(length=50), nullable=False),
    sa.Column('notification_sent', sa.Boolean(), nullable=False),
    sa.Column('confirmation_required', sa.Boolean(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointment_reschedules_appointment_id'), 'appointment_reschedules', ['appointment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_appointment_reschedules_appointment_id'), table_name='appointment_reschedules')
    op.drop_table('appointment_reschedules')
    op.drop_index(op.f('ix_appointment_attachments_appointment_id'), table_name='appointment_attachments')
    op.drop_table('appointment_attachments')
    op.drop_index(op.f('ix_professional_services_professional_id'), table_name='professional_services')
    op.drop_table('professional_services')
    op.drop_index(op.f('ix_professional_availability_professional_id'), table_name='professional_availability')
    op.drop_index(op.f('ix_professional_availability_date'), table_name='professional_availability')
    op.drop_table('professional_availability')
    op.drop_index(op.f('ix_appointments_status'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_scheduled_date'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_professional_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_patient_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_appointment_number'), table_name='appointments')
    op.drop_table('appointments')
    op.drop_index(op.f('ix_appointment_statistics_date'), table_name='appointment_statistics')
    op.drop_table('appointment_statistics')
    op.drop_index(op.f('ix_medical_services_specialty'), table_name='medical_services')
    op.drop_index(op.f('ix_medical_services_code'), table_name='medical_services')
    op.drop_index(op.f('ix_medical_services_category'), table_name='medical_services')
    op.drop_table('medical_services')
    op.drop_index(op.f('ix_appointment_locations_code'), table_name='appointment_locations')
    op.drop_table('appointment_locations')
    # ### end Alembic commands ###
